### PR TITLE
Add articles download

### PR DESCRIPTION
**Pull request by vlasy**
based on PR#17

### CODE REVIEW

**Comment by xmarj112** [comment]
Hello,

Did it run ok locally? Because there is no change to the api/model.py

I had issue with using flask_sqlalchemy outside of flask for the db connection, it seemed it is not supported, that is why I have changed also the model to use sqlalchemy, which can be used in flask and outside aswell, It came with also with different object access. (As I have described in the original PR)

old: Questions.query.get(questionID)
new: db.session.query(Questions).get(questionID)

Thanks,

Jan

**Comment by vlasy** [comment]
> 
> Did it run ok locally? Because there is no change to the api/model.py
> 


Yes, I tried running it locally and all the DB entries were created successfully

**Comment by xmarj112** [comment]
If yes, i would merge it and see if it works. (only thing the DB connstr is at localhost)

**Comment by pavelbartos** [comment]
upload data cron

**Pull request merged**
